/*
 * MIT License
 *
 * Copyright (c) 2018-2021 Davide Angelocola
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package hosh.runtime;

import hosh.doc.Todo;
import hosh.spi.Command;
import hosh.spi.Errors;
import hosh.spi.ExitStatus;
import hosh.spi.InputChannel;
import hosh.spi.Key;
import hosh.spi.Keys;
import hosh.spi.OutputChannel;
import hosh.spi.Record;
import hosh.spi.State;
import hosh.spi.StateAware;
import hosh.spi.StateMutator;
import hosh.spi.StateMutatorAware;
import hosh.spi.Value;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

// generated by compiler for 'cmd | { key -> cmd ${path} }'
class LambdaCommand implements Command, InterpreterAware, StateAware, StateMutatorAware {

	private final Compiler.Statement statement;
	private final String key;
	private Interpreter interpreter;
	private State state;
	private StateMutator stateMutator;

	public LambdaCommand(Compiler.Statement statement, String key) {
		this.statement = statement;
		this.key = key;
	}

	@Override
	public void setInterpreter(Interpreter interpreter) {
		this.interpreter = interpreter;
	}

	@Override
	public void setState(State state) {
		this.state = state;
	}

	@Override
	public void setStateMutator(StateMutator stateMutator) {
		this.stateMutator = stateMutator;
	}

	@Todo(description = "generalize with a list of keys")
	@Override
	public ExitStatus run(List<String> args, InputChannel in, OutputChannel out, OutputChannel err) {
		Key internedKey = Keys.of(key);
		for (Record record : InputChannel.iterate(in)) {
			Optional<Value> lambdaParameter = record.value(internedKey);
			if (lambdaParameter.isEmpty()) {
				err.send(Errors.message("missing key '%s'", key));
				return ExitStatus.error();
			}
			Value value = lambdaParameter.orElseThrow(IllegalArgumentException::new);
			Map<String, String> original = state.getVariables();
			Map<String, String> modified = new HashMap<>(original);
			modified.put(key, value.unwrap(String.class).orElse("unwrap failed"));
			stateMutator.mutateVariables(modified); // beware: global state is mutated here, this change should be local
			try {
				ExitStatus eval = interpreter.eval(statement, in, out, err);
				if (eval.isError()) {
					return eval;
				}
			} finally {
				// any change made by inner statement to variable will be lost here
				stateMutator.mutateVariables(original);
			}
		}
		return ExitStatus.success();
	}

	public String getKey() {
		return key;
	}
}
